server:
  port: 8090
spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 20MB #单个文件最大为20M
      max-request-size: 20MB #单个文件最大为20M
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  freemarker:
    suffix: .html
    settings:
      classic_compatible: true
      template_update_delay: 0
      #设置freemarker全局的日期、时间格式
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
    cache: false
    request-context-attribute: request
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    content-type: text/html;charset=UTF-8


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/db_cms
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: P123456

  flyway:
    enabled: true
#    baseline-on-migrate: true
  mail:
    host: smtp.mxhichina.com
    username: ####
    password:  ####
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            instanceName: clusteredScheduler
            wrapJobExecutionInUserTransaction: false
            rmi:
              export: false
              proxy: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 20
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          jobStore:
            isClustered: true
            useProperties: true
            clusterCheckinInterval: 15000
            misfireThreshold: 50000
            tablePrefix: QRTZ_
            class: org.quartz.impl.jdbcjobstore.JobStoreTX

#    clean-disabled: true
#    schemas:
#      - cms_category
#      - cms_article
#      - cms_ad


auth:
  jwt:
    key-alias: jwt
    key-store: jwt.jks
    key-password: 123qwe
    key-store-password: 123qwe
    secret: Y21zMTIzcXdlCg==
    algorithm: RS512 #HS512
    expired: 18000
template:
  name: default

mail:
  from: ####
  from-name: CMS系统管理员

origin:
  access-control-allow-origin: http://localhost:9527,http://localhost:8095
code:
  expiration: 5

location:
  temp:
    user: true
    directory: /.cms/file/tmp

upload:
  # local 、aliyun 、qiniu
  type: local
  local:
    path: upload/file/
    url-prefix: http://localhost:8090/
  aliyun:
    support-cname: true
    endpoint: 111
    access-key-id: 111
    access-key-secret: 111
    bucket-name: 111
    url-prefix: 111
  qiniu:
    access-key: 111
    secret-key: 111
    bucket: 111
    region: auto
    url-prefix: 111



